#version 450 core

layout (
    local_size_x = 8,
    local_size_y = 8,
    local_size_z = 1
) in;


#define OUTPUT_W 1024
#define OUTPUT_H 1024
layout (binding = 0, rgba16f) uniform image2D un_output;


void main()
{
    ivec2 texel = ivec2(gl_GlobalInvocationID.xy);
    vec2  coord = vec2(texel) / vec2(OUTPUT_W, OUTPUT_H);
    vec3  color = vec3(coord.x, coord.y, coord.x*coord.y);
    imageStore(un_output, texel, vec4(color, 1.0));
}
